on:
    push:
      # Sequence of patterns matched against refs/tags
      tags:
        - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
    build:
        name: Create Release
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
          - uses: actions/setup-node@v3
            with:
              node-version: '16.x'
              registry-url: 'https://registry.npmjs.org'
          - run: npm install
          - run: npm publish --access public
            env:
              NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH }}
          - run: npm ci
          - run: npm build
          - name: git config
            run: |
                git config --global user.name "Vinod Kumar B"
                git config --global user.email "vbainapalli@loginsoft.com"
          - run: npm version major
          - run: npm publish
          - run: npm run release