name: 'Publish the package with the version mentioned in the tags'

on:
    push:
        # Sequence of patterns matched against refs/heads
        branches: ['main']
        # Sequence of patterns matched against refs/tags
        tags:
          - v1.*

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          # Setup .npmrc file to publish to npm
          - uses: actions/setup-node@v3
            with:
              node-version: '16.x'
          - run: npm ci
          - run: npm version minor
          - run: npm run build